spring:
  datasource:
    url: $(DB_URL)
    username: $(DB_USERNAME)
    password: $(DB_PASSWORD)
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false


server:
  error:
    include-message: always
  port: 5000