spring:
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 50MB # 한개 요청의 최대 사이즈 (default: 10MB)
  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    access-key: $(AWS_ACCESS_KEY_ID)
    secret-key: $(AWS_SECRET_ACCESS_KEY)
    bucket: $(AWS_RESOURCE_BUCKET)
    stack.auto: false

jwt:
  secret: $(JWT_SECRET_KEY)
  access-token-expiration: 86400000000
  refresh-token-expiration: 604800000